#!/usr/bin/env python3
"""
Free Food Fetcher - Full Version
=================================

Multi-source food detection for JHU students.
Actually uses Ara's web browsing + shows integration points.
"""

import ara_sdk as ara
from datetime import datetime, timezone
from typing import List


@ara.tool(id="get_time")
def get_time() -> dict:
    """Get current time."""
    now = datetime.now(timezone.utc)
    return {"time": now.isoformat(), "day": now.strftime("%A")}


@ara.tool(id="detect_food")
def detect_food(text: str) -> dict:
    """Analyze text for food signals."""
    text = text.lower()
    signals = []
    score = 0

    high = ["free pizza", "free food", "lunch provided", "chipotle", "catered"]
    med = ["refreshments", "snacks", "reception", "coffee"]

    for s in high:
        if s in text:
            signals.append(s)
            score += 30
    for s in med:
        if s in text:
            signals.append(s)
            score += 15

    return {"score": min(score, 100), "signals": signals, "has_food": score >= 40}


# Main agent with real browsing instructions
freefood = ara.Automation(
    id="freefood-full",
    system_instructions="""
You are Free Food Fetcher for JHU students. Find FREE FOOD on campus.

## YOUR MISSION
Search multiple sources and report any free food events.

## SOURCES TO CHECK (in order)

### 1. JHU Official (BROWSE THESE)
Actually visit and read:
- https://hub.jhu.edu/events/
- https://studentaffairs.jhu.edu/calendar/

Look for: events today/tomorrow, any food mentions

### 2. Instagram Accounts (DESCRIBE WHAT TO CHECK)
If you had Instagram access, you'd check:
- @jhuhopkins (main JHU account)
- @hopkinsstudents (student life)
- @jaborhopkins (programming board)
- @jhuacm (CS club - often has pizza)
- @jhuswe (software engineering club)

### 3. Common Food Events at JHU
These typically have free food:
- Club meetings (usually pizza)
- Tech talks (often catered)
- Career fairs (snacks)
- Study breaks (late night food)
- Department seminars (lunch provided)

## OUTPUT FORMAT

# 🍕 JHU FREE FOOD REPORT
*Generated by Free Food Fetcher on Ara*

## ✅ CONFIRMED FREE FOOD
[Events you found with actual food mentions]

## 🤔 LIKELY FREE FOOD
[Events that typically have food]

## 📱 SOCIAL MEDIA TO CHECK
[Instagram accounts students should follow]

## ⏰ NEXT SCAN
Ara will check again in 1 hour.

---
Be helpful and enthusiastic! Students love free food.
""",
    tools=[get_time, detect_food],
    allow_connector_tools=True,
)


if __name__ == "__main__":
    print("""
╔═══════════════════════════════════════════════════════════════════════════╗
║  🍕 FREE FOOD FETCHER - FULL VERSION                                      ║
╠═══════════════════════════════════════════════════════════════════════════╣
║                                                                           ║
║  Sources:                                                                 ║
║  ├── 🌐 JHU Event Calendars (Ara browses these)                          ║
║  ├── 📸 Instagram tips (tells you what to check)                         ║
║  ├── 💬 GroupMe integration (future)                                     ║
║  └── 📧 Email scanning (future with OAuth)                               ║
║                                                                           ║
║  Deploy: ara deploy freefood_full.py --cron "0 * * * *"                  ║
║  Run:    ara run freefood_full.py                                         ║
║                                                                           ║
╚═══════════════════════════════════════════════════════════════════════════╝
""")
